name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.1'
      - run: npm ci
      # - run: npm run build --if-present ## not need
      - run: npm test